language: python
python: 3.6.9

env:
  DOCKER_COMPOSE_VERSION: 1.25.4
services:
  - docker

jobs:
  include:
    - stage: Testing
      install: pip install -r src/requirements.txt
      script: pytest src

    - stage: container creation and publishing
      install: skip
      script: travis/containerCreation.sh um-user-profile
      
    - stage: Static Code Analysis    
      language: java
      if: branch = develop
      before_install:
        - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
        - unzip sonar-scanner-cli-3.3.0.1492-linux.zip -d /tmp
      script: /tmp/sonar-scanner-3.3.0.1492-linux/bin/sonar-scanner -Dsonar.projectKey=$SONARQUBE_PROJECT_KEY -Dsonar.sources=. -Dsonar.host.url=$SONARQUBE_URL -Dsonar.login=$SONAR_TOKEN


    - stage: smoke and acceptance test
      install: skip # without this there's a `git clone` executed!
      script: travis/acceptanceTest.sh um-user-profile 8080 7000 # Service name + external port + internal port for docker

    - stage: release
      if: branch = master AND NOT type IN (pull_request)
      install: skip
      script: travis/release.sh um-user-profile

import:
  - docs/.travis.yml

notifications:
  slack: eoepca:Msk9hjQKAbwSYcVWiepenPim
#  email:
#    recipients:
#      - a.person@acme.com
#      - a.n.other@acme.com
  on_success: change # default: change
  on_failure: always # default: always
