[[mainOverview]]
= Overview

== Building Block Overview

[NOTE]
.Content Description
================================
This section contains:

* High-Level Description of the Building Block
* Context within EOEPCA
================================

The Login Service building block provides an OIDC and UMA compliant solution enabling authentication and authorization mechanisms within an Exploitation Platform. Other building blocks, such as the Policy Decision Point, Policy Enforcement Point and User Profile rely on this Building Block to provide several standard interfaces.

As stated in the EOEPCA Master System Design Document (ref. [PENDING]), the Login Service establishes itself as a client (Relying Party) for external Identity Providers (IDPs) allowing users coming from external domains to authenticate into the Exploitation Platform. In addition to this functionality, the Login Service also allows any Platform component to authenticate itself (without the need for an End-User to initiate the flow) therefore facilitating security aspects of the internal workflows of a Platform.

The figure below, identifies the main workflows on which the Login Service participates:

[[IMAGE]]

Based on this workflows, the Login Service enables the following functionality aspects

=== End-User Authentication through external IDPs

The Login Service establishes itself as a client to all supported external IDPs, with the necessary trust relationships in place to support the authentication flow. End-Users participating in this flow will propagate - with their necessary consent - a subset of the information stored in the external IDP into the Login Service back-end in order to facilitate unique identification of users and the Billing and Accounting functionalities of the overall Platform.

==== Authentication Flow

The following image indicates the sequence of events necessary for a user to authenticate using an external Identity Provider (IDP).

[[IMAGE]]

==== Unique identification of End-Users

By default, the Login Service extracts the email account stored in the external Identity Provider and checks that the user has not logged in previously with any other external IDP under the same email account. Whenever that's the case, the authentication flow skips the persistence of End-User attributes to the back-end and directly considers the user authenticated.

=== Single Sign-On

Single Sign-On (SSO) comes as one of the main benefits of using OIDC as authentication standard, allowing Service Providers (Client Applications) that utilize the Login Service to skip the step that requires input of credentials by the end-user if the Login Service detects that a session for the user is ongoing within the platform.

=== Single Log-Out

Similar to the SSO functionality, applications can request the End-User session can be terminated across the platform, and register themselves to receive this log-out request (in order to also handle it internally).

== Static Architecture

[NOTE]
.Content Description
================================
This section contains:

* Diagram and description of the major logical components within the Building Block

================================

The Login Service, heavily relies on Free and Open Source Software that already implements the interfaces and functionality required. The following image depicts the Static Architecture of this Building Block.

[[IMAGE]]

* The Authentication and Authorization Service enables both OIDC and UMA flows for the whole Platform
* The Administration Service provides and Administration GUI and a SCIM Implementation allowing direct interaction with the End-User Back-End
* The Back-End Service stores the necessary information for the other components to provide Session Management, Authorization and persists external IDP information generated or relayed during authentication.
* The Relying Party component allows to register as a RP in any external IDP.

The Section for the Building Block Design [REF] contains detailed descriptions and references to the Open Source components used in this Building Block.

== Use Cases

[NOTE]
.Content Description
================================
This section contains:

* Diagrams and definition of the use cases covered by this Building Block

================================

== External Interfaces

[NOTE]
.Content Description
================================
This section contains:

* Listing of technical external interfaces (with other Building Blocks)

================================

=== Authentication (AuthN) Interface

The Login Service exposes an OpenID Connect interface through a .well-known URI that describes all standard endpoints

=== Authorization (AuthZ) Interface

The Login Service exposes a User Managed Access (UMA) interface through a .well-known URI that describes all standard endpoints

=== Identity Management Interface

The Login Service exposes a System for Cross Domain Identity (SCIM) Interface through a .well-known URI that describes all standard endpoints

=== Administration Interface

A web service is made available for administrators and operators to manage the configuration aspects of the Login Service without the need to authenticate using external IDPs.

=== External IDP Discovery Interface

A landing web page interface for Authentication Requests is made available, allowing users to select their preferred external IDP and initiate authentication flow.

== Required Resources

[NOTE]
.Content Description
================================
This section contains:

* List of HW and SW required resources for the correct functioning of the building Block
* References to open repositories (when applicable)

================================

=== Software

The following Open-Source Software is required to support the deployment and integration of the Login Service:

* Authentication and Authorization Service
** oxAuth - Gluu Inc. [LINK to Github]
* Administration Service
** oxTrust - Gluu Inc. (Link to Github)
* Back-end Service
** OpenDJ/LDAP Distribution (Link to Github)
* OIDC Compliant, extensible Relying Party
** Passport.js (Link to Github)
* Deployment, Configuration and Integration Tooling
** Persistence system load/backup/restore components (Link to Github)
** Kubernetes secret and config Tooling (Link to Github)
** Reverse Proxy exposing API interfaces - Nginx/Ingress


== Design Standards, Conventions and Procedures

[NOTE]
.Content Description
================================
This section contains:

* Explanations on the UML Design notation and necessary naming conventions used throughout the document

================================

=== UML Design
=== Naming Conventions
