apiVersion: v1
kind: Service
metadata:
  name: user-profile
  labels:
    app: user-profile
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http-up
    protocol: TCP
  - port: 443
    name: https-up
    targetPort: 443
    protocol: TCP
  selector:
    app: user-profile

---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: user-profile
    labels:
        app: user-profile
spec:
    replicas: 1
    selector:
        matchLabels:
            app: user-profile
    template:
        metadata:
            labels:
                app: user-profile
        spec:
            containers:
            - name: user-profile
              imagePullPolicy: Always
              image: eoepca/um-user-profile:latest
              ports:
                - containerPort: 80
                  name: http-up
                - containerPort: 443
                  name: https-up
              envFrom:
                - configMapRef:
                    name: um-user-profile-config
            hostAliases:
            - ip: NGINX_IP
              hostnames:
              - {{GLUU_DOMAIN}}  
            volumes:
            - name: user-profile-logs
              persistentVolumeClaim:
                claimName: user-profile-logs-volume-claim
            - name: user-profile-lib-ext
              persistentVolumeClaim:
                claimName: user-profile-lib-ext-volume-claim
            - name: user-profile-custom-static
              persistentVolumeClaim:
                claimName: user-profile-custom-static-volume-claim
            - name: user-profile-custom-pages
              persistentVolumeClaim:
                claimName: user-profile-custom-pages-volume-claim
