apiVersion: v1
kind: Service
metadata:
  name: user-profile
  labels:
    app: user-profile
spec:
  ports:
  - port: 5566
    protocol: TCP
    name: user-profile
  selector:
    app: user-profile

---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: user-profile
    labels:
        app: user-profile
spec:
    replicas: 1
    selector:
        matchLabels:
            app: user-profile
    template:
        metadata:
            labels:
                app: user-profile
        spec:
            containers:
            - name: user-profile
              imagePullPolicy: Always
              image: eoepca/um-user-profile:travis_25
              ports:
              - containerPort: 5566
            hostAliases:
            - ip: NGINX_IP
              hostnames:
              - {{GLUU_DOMAIN}}  
            volumes:
            - name: user-profile-logs
              persistentVolumeClaim:
                claimName: user-profile-logs-volume-claim
            - name: user-profile-lib-ext
              persistentVolumeClaim:
                claimName: user-profile-lib-ext-volume-claim
            - name: user-profile-custom-static
              persistentVolumeClaim:
                claimName: user-profile-custom-static-volume-claim
            - name: user-profile-custom-pages
              persistentVolumeClaim:
                claimName: user-profile-custom-pages-volume-claim
