
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.context }}-service-static
  
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls: 
   - secretName: user-profile-tls-certificate
     hosts:
       - demoexample.gluu.org
  rules:
  - host: {{ .Values.global.domain | quote }}
    http:
      paths:
      - path: /static
        backend:
          serviceName: {{ .Values.global.user }}
          servicePort: {{ .Values.global.servicePort }}



---


apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.context }}-service
  
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls: 
   - secretName: user-profile-tls-certificate
     hosts:
       - demoexample.gluu.org
  rules:
  - host: {{ .Values.global.domain | quote }}
    http:
      paths:
      - path: {{ .Values.global.baseUri }}
        backend:
          serviceName: {{ .Values.global.user }}
          servicePort: {{ .Values.global.servicePort }}
