# This is a basic workflow to help you get started with Actions

name: User-Profile Documentation

# Controls when the action will run. 
on: push
  # Triggers the workflow on push or pull request events but only for the develop branch


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    env:
      GH_USER_NAME: ${{ secrets.GH_USER_NAME }}
      GH_USER_EMAIL: ${{ secrets.GH_USER_EMAIL }}
      GH_REPOS_NAME: ${{ secrets.GH_REPOS_NAME }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Generate the docs
        run: ./docs/bin/generate-docs.sh
      - name: Publish the docs
        run: ./docs/bin/publish-docs.sh
