# This is a basic workflow to help you get started with Actions

name: PDP Engine Test Workflow

# Controls when the action will run. 
on: push
  # Triggers the workflow on push or pull request events but only for the develop branch
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  prepare-system:
    # Name the Job
    name: Prepare system to run tests
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python 3.6.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.9
      - name: Install ubuntu dependencies
        run: sudo apt-get install jq python3-venv virtualenv
      - name: Change to main folder
        run: cd ..
      - name: Create python env
        run: python3 -m venv env
      - name: Activate environment
        run: source env/bin/activate
      - name: Install requirements
        run: pip3 install -r src/requirements.txt

      # - name: Create flask env
      #   run: virtualenv flask
      # - name: Activate environment
      #   run: |
      #     cd flask
      #     source bin/activate
      #     cd ..
      #     pip install -r src/requirements.txt
      #     pip uninstall -y flask && python -m pip install flask
      - name: Run main
        run: python src/web_main.py
      - name: Installing robotframework
        run: pip3 install robotframework
      - name: Installing Chrome and Drivers
        run: sudo ./gh_actions/install-chromedriver.sh
      - name: Activate env
        run:  source $HOME/.local/robot/bin/activate
      - name: Run tests
        run: robot ./tests
